services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    hostname: redis
    image: redis:8-alpine
    ports:
      - "6379:6379"
    restart: on-failure
  auth:
    build: ./backend/auth
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
  bookkeeping:
    build: ./backend/bookkeeping
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
volumes:
  postgres_data: